[package]
name = "in-lepus-foraminis"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy-inspector-egui = "0.24.0"
concursus = { path = "../concursus" }
physica = { path = "../physica" }
